export const environments = [
  "todos",
  "deserto",
  "floresta",
  "caverna",
  "montanha",
  "pântano",
  "subterrâneo",
  "tundra",
  "ruínas",
  "vulcão",
  "planície",
  "mar",
  "céu",
  "selva",
  "cemitério",
  "castelo",
  "cidade",
  "espaço"
] as const;

export type Environment = (typeof environments)[number];

export const monsterImages = [
  'bat', 'cat', 'crab', 'deer', 'dire-wolf', 'draft-horse', 'giant-goat', 'druid', 'eagle', 'elephant', 'elk', 'frog', 'giant-ape', 'giant-badger',
  'giant-bat', 'giant-boar', 'giant-centipede', 'giant-constrictor-snake', 'giant-crab', 'giant-crocodile', 'giant-eagle', 'giant-elk', 'giant-fire-beetle', 'giant-frog',
  'giant-goat', 'giant-hyena', 'giant-lizard', 'giant-octopus', 'giant-owl', 'giant-poisonous-snake', 'giant-rat', 'giant-rat-diseased', 'giant-scorpion', 'giant-sea-horse', 'giant-shark',
  'giant-spider', 'giant-toad', 'giant-vulture', 'giant-wasp', 'giant-weasel', 'giant-wolf-spider', 'goat', 'guard', 'hawk', 'hunter-shark', 'hyena', 'killer-whale', 'jackal', 'knight', 'lemure',
  'lion', 'lizard', 'mage', 'mammoth', 'mule', 'octopus', 'owl', 'panther', 'poisonous-snake', 'polar-bear', 'pony', 'priest', 'quipper', 'rat', 'raven', 'reef-shark', 'rhinoceros',
  'riding-horse', 'scorpion', 'sea-horse', 'spider', 'spy', 'succubus-incubus', 'swarm-of-bats', 'swarm-of-beetles', 'swarm-of-centipedes', 'swarm-of-insects', 'swarm-of-poisonous-snakes',
  'swarm-of-quippers', 'swarm-of-rats', 'swarm-of-ravens', 'swarm-of-spiders', 'swarm-of-wasps', 'tiger', 'vulture', 'werebear-human', 'werebear-hybrid', 'wereboar-human', 'wereboar-hybrid',
  'wererat-human', 'wererat-hybrid', 'weretiger-human', 'weretiger-hybrid', 'werewolf-human', 'werewolf-hybrid'
];

export const monsterTypes: Record<string, 'humano' | 'dragao' | 'animal'> = {
  // Humanos
  'acolyte': 'humano',
  'archmage': 'humano',
  'assassin': 'humano',
  'bandit': 'humano',
  'bandit-captain': 'humano',
  'berserker': 'humano',
  'commoner': 'humano',
  'cult-fanatic': 'humano',
  'cultist': 'humano',
  'doppelganger': 'humano',
  'druid': 'humano',
  'gladiator': 'humano',
  'guard': 'humano',
  'knight': 'humano',
  'mage': 'humano',
  'noble': 'humano',
  'priest': 'humano',
  'scout': 'humano',
  'spy': 'humano',
  'thug': 'humano',
  'tribal-warrior': 'humano',
  'veteran': 'humano',

  // Dragões
  'adult-black-dragon': 'dragao',
  'adult-blue-dragon': 'dragao',
  'adult-brass-dragon': 'dragao',
  'adult-bronze-dragon': 'dragao',
  'adult-copper-dragon': 'dragao',
  'adult-gold-dragon': 'dragao',
  'adult-green-dragon': 'dragao',
  'adult-red-dragon': 'dragao',
  'adult-silver-dragon': 'dragao',
  'adult-white-dragon': 'dragao',
  'ancient-black-dragon': 'dragao',
  'ancient-blue-dragon': 'dragao',
  'ancient-brass-dragon': 'dragao',
  'ancient-bronze-dragon': 'dragao',
  'ancient-copper-dragon': 'dragao',
  'ancient-gold-dragon': 'dragao',
  'ancient-green-dragon': 'dragao',
  'ancient-red-dragon': 'dragao',
  'ancient-silver-dragon': 'dragao',
  'ancient-white-dragon': 'dragao',
  'black-dragon-wyrmling': 'dragao',
  'blue-dragon-wyrmling': 'dragao',
  'brass-dragon-wyrmling': 'dragao',
  'bronze-dragon-wyrmling': 'dragao',
  'copper-dragon-wyrmling': 'dragao',
  'gold-dragon-wyrmling': 'dragao',
  'green-dragon-wyrmling': 'dragao',
  'red-dragon-wyrmling': 'dragao',
  'silver-dragon-wyrmling': 'dragao',
  'white-dragon-wyrmling': 'dragao',
  'young-black-dragon': 'dragao',
  'young-blue-dragon': 'dragao',
  'young-brass-dragon': 'dragao',
  'young-bronze-dragon': 'dragao',
  'young-copper-dragon': 'dragao',
  'young-gold-dragon': 'dragao',
  'young-green-dragon': 'dragao',
  'young-red-dragon': 'dragao',
  'young-silver-dragon': 'dragao',
  'young-white-dragon': 'dragao',
  'half-red-dragon-veteran': 'dragao',

  // Animais
  'ape': 'animal',
  'axe-beak': 'animal',
  'baboon': 'animal',
  'badger': 'animal',
  'bat': 'animal',
  'black-bear': 'animal',
  'blood-hawk': 'animal',
  'boar': 'animal',
  'brown-bear': 'animal',
  'camel': 'animal',
  'cat': 'animal',
  'constrictor-snake': 'animal',
  'crab': 'animal',
  'crocodile': 'animal',
  'deer': 'animal',
  'dire-wolf': 'animal',
  'draft-horse': 'animal',
  'eagle': 'animal',
  'elephant': 'animal',
  'elk': 'animal',
  'flying-snake': 'animal',
  'frog': 'animal',
  'giant-ape': 'animal',
  'giant-badger': 'animal',
  'giant-bat': 'animal',
  'giant-boar': 'animal',
  'giant-centipede': 'animal',
  'giant-constrictor-snake': 'animal',
  'giant-crab': 'animal',
  'giant-crocodile': 'animal',
  'giant-eagle': 'animal',
  'giant-elk': 'animal',
  'giant-fire-beetle': 'animal',
  'giant-frog': 'animal',
  'giant-goat': 'animal',
  'giant-hyena': 'animal',
  'giant-lizard': 'animal',
  'giant-octopus': 'animal',
  'giant-owl': 'animal',
  'giant-poisonous-snake': 'animal',
  'giant-rat': 'animal',
  'giant-rat-diseased': 'animal',
  'giant-scorpion': 'animal',
  'giant-sea-horse': 'animal',
  'giant-shark': 'animal',
  'giant-spider': 'animal',
  'giant-toad': 'animal',
  'giant-vulture': 'animal',
  'giant-wasp': 'animal',
  'giant-weasel': 'animal',
  'giant-wolf-spider': 'animal',
  'goat': 'animal',
  'hawk': 'animal',
  'horse': 'animal',
  'hunter-shark': 'animal',
  'hyena': 'animal',
  'jackal': 'animal',
  'killer-whale': 'animal',
  'lion': 'animal',
  'lizard': 'animal',
  'mastiff': 'animal',
  'mammoth': 'animal',
  'owl': 'animal',
  'panther': 'animal',
  'plesiosaurus': 'animal',
  'poisonous-snake': 'animal',
  'polar-bear': 'animal',
  'pony': 'animal',
  'quipper': 'animal',
  'rat': 'animal',
  'raven': 'animal',
  'reef-shark': 'animal',
  'remorhaz': 'animal',
  'rhinoceros': 'animal',
  'riding-horse': 'animal',
  'saber-toothed-tiger': 'animal',
  'scorpion': 'animal',
  'sea-hag': 'animal',
  'sea-horse': 'animal',
  'shark': 'animal',
  'squid': 'animal',
  'swan': 'animal',
  'tiger': 'animal',
  'triceratops': 'animal',
  'tyrannosaurus-rex': 'animal',
  'vulture': 'animal',
  'warhorse': 'animal',
  'weasel': 'animal',
  'wolf': 'animal',
  'worg': 'animal',
};