    // deserto
    // floresta
    // caverna
    // montanha
    // pântano
    // subterrâneo
    // tundra
    // ruínas
    // vulcão
    // planície
    // mar
    // céu
    // selva
    // cemitério
    // castelo
    // cidade
    // espaço
    // todos
    export const monsterEnvironments: Record<string, string[]> = {
    'aboleth': ['subterrâneo', 'mar'],
    'acolyte': ['todos'],
    'adult-black-dragon': ['caverna', 'montanha', 'ruínas'],
    'adult-blue-dragon': ['caverna', 'montanha', 'ruínas', 'mar'],
    'adult-brass-dragon': ['caverna', 'montanha', 'ruínas', 'subterrâneo'],
    'adult-bronze-dragon': ['caverna', 'montanha', 'ruínas', 'subterrâneo', 'deserto'],
    'adult-copper-dragon': ['caverna', 'montanha', 'ruínas', 'subterrâneo'],
    'adult-gold-dragon': ['caverna', 'montanha', 'ruínas', 'subterrâneo'],
    'adult-green-dragon': ['caverna', 'montanha', 'ruínas', 'floresta'],
    'adult-red-dragon': ['caverna', 'montanha', 'ruínas', 'vulcão'],
    'adult-silver-dragon': ['caverna', 'montanha', 'ruínas', 'subterrâneo'],
    'adult-white-dragon': ['caverna', 'montanha', 'ruínas', 'tundra'],
    'air-elemental': ['floresta', 'montanha', 'céu'],
    'ancient-black-dragon': ['caverna', 'montanha', 'ruínas'],
    'ancient-blue-dragon': ['caverna', 'montanha', 'ruínas', 'mar'],
    'ancient-brass-dragon': ['caverna', 'montanha', 'ruínas', 'subterrâneo'],
    'ancient-bronze-dragon': ['caverna', 'montanha', 'ruínas', 'subterrâneo', 'deserto'],
    'ancient-copper-dragon': ['caverna', 'montanha', 'ruínas', 'subterrâneo'],
    'ancient-gold-dragon': ['caverna', 'montanha', 'ruínas', 'subterrâneo'],
    'ancient-green-dragon': ['caverna', 'montanha', 'ruínas', 'subterrâneo'],
    'ancient-red-dragon': ['caverna', 'montanha', 'ruínas', 'vulcão'],
    'ancient-silver-dragon': ['caverna', 'montanha', 'ruínas', 'subterrâneo'],
    'ancient-white-dragon': ['caverna', 'montanha', 'ruínas', 'tundra'],
    'androsphinx': ['deserto', 'planície', 'montanha', 'ruínas'],
    'animated-armor': ['castelo', 'ruína'],
    'ankheg': ['planície', 'floresta', 'selva', 'subterrâneo'],
    'ape': ['floresta', 'selva'],
    'archmage': ['todos'],
    'assassin': ['todos'],
    'awakened-shrub': ['floresta', 'selva', 'planície'],
    'awakened-tree': ['floresta', 'selva'],
    'axe-beak': ['planície', 'tundra'],
    'azer': ['vulcão', 'subterrâneo'],
    'baboon': ['selva', 'floresta', 'montanha', 'deserto'],
    'badger': ['floresta', 'planície', 'subterrâneo'],
    'balor': ['vulcão', 'subterrâneo', 'ruínas'],
    'bandit': ['todos'],
    'bandit-captain': ['todos'],
    'barbed-devil': ['subterrâneo', 'vulcão', 'ruínas'],
    'basilisk': ['caverna', 'subterrâneo', 'floresta', 'deserto', 'montanha'],
    'bat': ['caverna', 'floresta', 'subterrâneo'],
    'bearded-devil': ['subterrâneo', 'vulcão', 'ruínas'],
    'behir': ['montanha', 'caverna', 'deserto'],
    'berserker': ['todos'],
    'black-bear': ['floresta', 'montanha', 'selva'],
    'black-dragon-wyrmling': ['caverna', 'montanha', 'ruínas'],
    'black-pudding': ['caverna', 'subterrâneo', 'ruínas'],
    'blink-dog': ['floresta', 'planície', 'selva'],
    'blood-hawk': ['floresta', 'selva', 'montanha', 'planície'],
    'blue-dragon-wyrmling': ['caverna', 'montanha', 'ruínas'],
    'boar': ['floresta', 'planície', 'selva'],
    'bone-devil': ['subterrâneo', 'vulcão', 'ruínas', 'cemitério'],
    'brass-dragon-wyrmling': ['caverna', 'montanha', 'ruínas'],
    'bronze-dragon-wyrmling': ['caverna', 'montanha', 'ruínas'],
    'brown-bear': ['floresta', 'montanha', 'selva'],
    'bugbear': ['caverna', 'floresta', 'montanha', 'ruínas'],
    'bulette': ['planície', 'montanha', 'subterrâneo'],
    'camel': ['deserto', 'planície'],
    'cat': ['cidade', 'planície', 'floresta'],
    'centaur': ['floresta', 'planície', 'selva'],
    'chain-devil': ['subterrâneo', 'vulcão', 'ruínas', 'cemitério'],
    'chimera': ['montanha', 'caverna', 'ruínas', 'deserto'],
    'chuul': ['pântano', 'subterrâneo', 'mar'],
    'clay-golem': ['castelo', 'ruínas', 'cemitério'],
    'cloaker': ['caverna', 'subterrâneo', 'ruínas'],
    'cloud-giant': ['montanha', 'céu'],
    'cockatrice': ['floresta', 'caverna', 'planície', 'montanha'],
    'commoner': ['todos'],
    'constrictor-snake': ['floresta', 'selva', 'pântano', 'caverna'],
    'copper-dragon-wyrmling': ['caverna', 'montanha', 'ruínas'],
    'couatl': ['selva', 'floresta', 'céu', 'planície'],
    'crab': ['mar', 'pântano'],
    'crocodile': ['pântano', 'mar', 'selva'],
    'cult-fanatic': ['todos'],
    'darkmantle': ['caverna', 'subterrâneo'],
    'death-dog': ['planície', 'floresta', 'ruínas', 'montanha', 'deserto'],
    'deep-gnome-svirfneblin': ['subterrâneo', 'caverna'],
    'deer': ['floresta', 'planície', 'selva', 'montanha'],
    'deva': ['céu', 'planície', 'montanha'],
    'dire-wolf': ['floresta', 'planície', 'tundra', 'montanha'],
    'djinni': ['céu', 'deserto', 'montanha'],
    'doppelganger': ['todos'],
    'draft-horse': ['planície', 'cidade'],
    'dragon-turtle': ['mar'],
    'dretch': ['subterrâneo', 'ruínas', 'vulcão', 'cemitério'],
    'drider': ['subterrâneo', 'caverna', 'ruínas'],
    'drow': ['todos'],
    'druid': ['todos'],
    'dryad': ['floresta', 'selva'],
    'duergar': ['caverna', 'subterrâneo', 'ruínas', 'vulcão', 'cemitério', 'castelo'],
    'dust-mephit': ['deserto', 'subterrâneo', 'ruínas'],
    'eagle': ['montanha', 'planície', 'floresta', 'céu'],
    'earth-elemental': ['caverna', 'montanha', 'subterrâneo'],
    'efreeti': ['vulcão', 'deserto', 'subterrâneo'],
    'elephant': ['planície', 'selva'],
    'elk': ['planície', 'montanha', 'floresta'],
    'erinyes': ['céu', 'subterrâneo', 'vulcão', 'ruínas'],
    'ettercap': ['floresta', 'selva', 'caverna'],
    'ettin': ['caverna', 'montanha', 'floresta', 'ruínas'],
    'fire-elemental': ['vulcão', 'subterrâneo', 'ruínas'],
    'fire-giant': ['vulcão', 'montanha', 'subterrâneo'],
    'flesh-golem': ['castelo', 'ruínas', 'cemitério'],
    'flying-snake': ['selva', 'floresta', 'planície', 'montanha'],
    'flying-sword': ['castelo', 'ruínas', 'cidade'],
    'frog': ['pântano', 'selva', 'floresta'],
    'frost-giant': ['tundra', 'montanha'],
    'gargoyle': ['castelo', 'ruínas', 'cidade', 'montanha'],
    'gelatinous-cube': ['caverna', 'subterrâneo', 'ruínas'],
    'ghast': ['cemitério', 'ruínas', 'subterrâneo'],
    'ghost': ['cemitério', 'castelo', 'ruínas', 'cidade'],
    'ghoul': ['cemitério', 'ruínas', 'subterrâneo'],
    'giant-ape': ['selva', 'floresta', 'montanha'],
    'giant-badger': ['floresta', 'planície', 'subterrâneo'],
    'giant-bat': ['caverna', 'subterrâneo', 'floresta'],
    'giant-boar': ['floresta', 'planície', 'selva'],
    'giant-centipede': ['caverna', 'subterrâneo', 'floresta', 'selva'],
    'giant-constrictor-snake': ['selva', 'floresta', 'pântano'],
    'giant-crab': ['mar', 'pântano'],
    'giant-crocodile': ['pântano', 'mar', 'selva'],
    'giant-eagle': ['montanha', 'céu', 'planície'],
    'giant-elk': ['planície', 'montanha', 'floresta'],
    'giant-fire-beetle': ['caverna', 'subterrâneo', 'floresta', 'selva'],
    'giant-frog': ['pântano', 'selva', 'floresta'],
    'giant-goat': ['montanha', 'planície'],
    'giant-hyena': ['planície', 'deserto', 'selva'],
    'giant-lizard': ['deserto', 'caverna', 'selva', 'floresta'],
    'giant-octopus': ['mar', 'caverna'],
    'giant-owl': ['floresta', 'planície', 'montanha', 'céu'],
    'giant-poisonous-snake': ['selva', 'floresta', 'pântano'],
    'giant-rat': ['cidade', 'subterrâneo', 'ruínas', 'caverna'],
    'giant-rat-diseased': ['cidade', 'subterrâneo', 'ruínas', 'caverna'],
    'giant-scorpion': ['deserto', 'caverna', 'subterrâneo'],
    'giant-sea-horse': ['mar'],
    'giant-shark': ['mar'],
    'giant-spider': ['floresta', 'selva', 'caverna', 'subterrâneo'],
    'giant-toad': ['pântano', 'selva', 'floresta'],
    'giant-vulture': ['deserto', 'planície', 'montanha', 'céu'],
    'giant-wasp': ['floresta', 'selva', 'planície'],
    'giant-weasel': ['floresta', 'planície', 'selva'],
    'giant-wolf-spider': ['floresta', 'selva', 'caverna', 'subterrâneo'],
    'gibbering-mouther': ['subterrâneo', 'caverna', 'pântano', 'ruínas'],
    'glabrezu': ['subterrâneo', 'ruínas', 'vulcão'],
    'gladiator': ['todos'],
    'gnoll': ['planície', 'deserto', 'floresta', 'selva', 'montanha'],
    'goat': ['montanha', 'planície'],
    'goblin': ['caverna', 'montanha', 'floresta', 'ruínas'],
    'gold-dragon-wyrmling': ['caverna', 'montanha', 'ruínas'],
    'gorgon': ['planície', 'montanha', 'floresta', 'ruínas'],
    'gray-ooze': ['caverna', 'subterrâneo', 'ruínas'],
    'green-dragon-wyrmling': ['caverna', 'montanha', 'ruínas'],
    'green-hag': ['pântano', 'floresta', 'selva', 'ruínas'],
    'grick': ['caverna', 'subterrâneo', 'montanha', 'ruínas'],
    'griffon': ['montanha', 'planície', 'céu'],
    'grimlock': ['subterrâneo', 'caverna', 'ruínas'],
    'guard': ['todos'],
    'guardian-naga': ['ruínas', 'caverna', 'selva', 'floresta'],
    'gynosphinx': ['deserto', 'planície', 'montanha', 'ruínas'],
    'half-red-dragon-veteran': ['caverna', 'montanha', 'ruínas'],
    'harpy': ['montanha', 'caverna', 'ruínas', 'deserto', 'pântano'],
    'hawk': ['floresta', 'planície', 'montanha', 'céu'],
    'hell-hound': ['subterrâneo', 'vulcão', 'ruínas', 'cemitério'],
    'hezrou': ['subterrâneo', 'pântano', 'ruínas', 'vulcão'],
    'hill-giant': ['montanha', 'planície', 'floresta'],
    'hippogriff': ['planície', 'montanha', 'céu', 'floresta'],
    'hobgoblin': ['caverna', 'montanha', 'floresta', 'ruínas'],
    'homunculus': ['castelo', 'cidade', 'ruínas'],
    'horned-devil': ['subterrâneo', 'vulcão', 'ruínas', 'cemitério'],
    'hunter-shark': ['mar'],
    'hydra': ['pântano', 'mar', 'caverna'],
    'hyena': ['planície', 'deserto', 'selva'],
    'ice-devil': ['tundra', 'subterrâneo', 'ruínas'],
    'ice-mephit': ['tundra', 'subterrâneo', 'montanha'],
    'imp': ['subterrâneo', 'ruínas', 'cidade', 'vulcão'],
    'invisible-stalker': ['subterrâneo', 'castelo', 'cidade', 'ruínas', 'céu'],
    'iron-golem': ['castelo', 'cidade', 'ruínas'],
    'jackal': ['deserto', 'planície'],
    'killer-whale': ['mar'],
    'knight': ['todos'],
    'kobold': ['caverna', 'subterrâneo', 'montanha', 'ruínas'],
    'kraken': ['mar'],
    'lamia': ['deserto', 'ruínas', 'planície'],
    'lemure': ['subterrâneo', 'vulcão', 'ruínas'],
    'lich': ['castelo', 'cemitério', 'ruínas', 'subterrâneo'],
    'lion': ['planície', 'deserto', 'selva'],
    'lizard': ['floresta', 'selva', 'caverna', 'deserto'],
    'lizardfolk': ['pântano', 'floresta', 'selva', 'mar'],
    'mage': ['todos'],
    'magma-mephit': ['vulcão', 'subterrâneo', 'montanha'],
    'magmin': ['vulcão', 'subterrâneo', 'montanha'],
    'mammoth': ['tundra', 'montanha', 'planície'],
    'manticore': ['montanha', 'deserto', 'planície', 'ruínas'],
    'marilith': ['subterrâneo', 'ruínas', 'vulcão'],
    'mastiff': ['planície', 'floresta', 'cidade', 'montanha'],
    'medusa': ['caverna', 'ruínas', 'subterrâneo', 'pântano'],
    'merfolk': ['mar'],
    'merrow': ['mar', 'caverna'],
    'mimic': ['castelo', 'cidade', 'ruínas', 'subterrâneo'],
    'minotaur': ['caverna', 'subterrâneo', 'ruínas'],
    'minotaur-skeleton': ['caverna', 'subterrâneo', 'ruínas', 'cemitério'],
    'mule': ['planície', 'montanha', 'cidade'],
    'mummy': ['deserto', 'ruínas', 'cemitério', 'subterrâneo'],
    'mummy-lord': ['deserto', 'ruínas', 'cemitério', 'subterrâneo'],
    'nalfeshnee': ['subterrâneo', 'ruínas', 'vulcão'],
    'night-hag': ['subterrâneo', 'pântano', 'ruínas', 'plano astral'],
    'nightmare': ['subterrâneo', 'vulcão', 'cemitério', 'ruínas', 'céu'],
    'noble': ['todos'],
    'ochre-jelly': ['caverna', 'subterrâneo', 'ruínas'],
    'octopus': ['mar'],
    'ogre': ['caverna', 'montanha', 'floresta', 'ruínas'],
    'ogre-zombie': ['caverna', 'subterrâneo', 'ruínas', 'cemitério'],
    'oni': ['caverna', 'montanha', 'subterrâneo', 'ruínas'],
    'orc': ['caverna', 'montanha', 'floresta', 'ruínas'],
    'otyugh': ['subterrâneo', 'ruínas', 'pântano', 'cidade'],
    'owl': ['floresta', 'planície', 'montanha'],
    'owlbear': ['floresta', 'selva', 'montanha'],
    'panther': ['floresta', 'selva', 'montanha'],
    'pegasus': ['montanha', 'planície', 'céu'],
    'phase-spider': ['caverna', 'subterrâneo', 'ruínas', 'floresta'],
    'pit-fiend': ['subterrâneo', 'vulcão', 'ruínas', 'cemitério'],
    'planetar': ['céu', 'planície', 'montanha'],
    'plesiosaurus': ['mar'],
    'poisonous-snake': ['floresta', 'selva', 'pântano', 'caverna'],
    'polar-bear': ['tundra', 'montanha'],
    'pony': ['planície', 'cidade', 'floresta'],
    'priest': ['todos'],
    'purple-worm': ['subterrâneo', 'caverna', 'deserto'],
    'quasit': ['subterrâneo', 'ruínas', 'cidade', 'vulcão'],
    'quipper': ['mar'],
    'rakshasa': ['cidade', 'ruínas', 'subterrâneo'],
    'rat': ['cidade', 'subterrâneo', 'ruínas', 'caverna'],
    'raven': ['floresta', 'planície', 'montanha', 'cidade'],
    'red-dragon-wyrmling': ['caverna', 'montanha', 'ruínas'],
    'reef-shark': ['mar'],
    'remorhaz': ['tundra', 'montanha', 'subterrâneo'],
    'rhinoceros': ['planície', 'selva', 'deserto'],
    'riding-horse': ['planície', 'cidade', 'floresta'],
    'roc': ['montanha', 'planície', 'céu'],
    'roper': ['caverna', 'subterrâneo', 'ruínas'],
    'rug-of-smothering': ['castelo', 'ruínas', 'cidade'],
    'rust-monster': ['caverna', 'subterrâneo', 'ruínas'],
    'saber-toothed-tiger': ['tundra', 'floresta', 'montanha', 'planície'],
    'sahuagin': ['mar'],
    'salamander': ['vulcão', 'subterrâneo'],
    'satyr': ['floresta', 'selva', 'planície'],
    'scorpion': ['deserto', 'planície', 'selva', 'floresta'],
    'scout': ['todos'],
    'sea-hag': ['mar', 'pântano', 'caverna'],
    'sea-horse': ['mar'],
    'shadow': ['cemitério', 'ruínas', 'subterrâneo'],
    'shambling-mound': ['pântano', 'floresta', 'selva'],
    'shield-guardian': ['castelo', 'cidade', 'ruínas'],
    'shrieker': ['caverna', 'subterrâneo'],
    'silver-dragon-wyrmling': ['caverna', 'montanha', 'ruínas'],
    'skeleton': ['cemitério', 'ruínas', 'subterrâneo'],
    'solar': ['céu', 'montanha', 'planície'],
    'specter': ['cemitério', 'ruínas', 'subterrâneo', 'castelo'],
    'spider': ['floresta', 'selva', 'caverna', 'subterrâneo'],
    'spirit-naga': ['caverna', 'ruínas', 'selva', 'floresta'],
    'sprite': ['floresta', 'selva'],
    'spy': ['todos'],
    'steam-mephit': ['subterrâneo', 'vulcão', 'mar'],
    'stirge': ['caverna', 'subterrâneo', 'pântano', 'ruínas'],
    'stone-giant': ['montanha', 'caverna'],
    'stone-golem': ['castelo', 'ruínas', 'cidade'],
    'storm-giant': ['mar', 'céu', 'montanha'],
    'succubus-incubus': ['cidade', 'ruínas', 'subterrâneo'],
    'swarm-of-bats': ['caverna', 'subterrâneo', 'floresta'],
    'swarm-of-beetles': ['floresta', 'selva', 'subterrâneo', 'caverna'],
    'swarm-of-centipedes': ['caverna', 'subterrâneo', 'floresta', 'selva'],
    'swarm-of-insects': ['floresta', 'selva', 'pântano'],
    'swarm-of-poisonous-snakes': ['floresta', 'selva', 'pântano', 'caverna'],
    'swarm-of-quippers': ['mar'],
    'swarm-of-rats': ['cidade', 'subterrâneo', 'ruínas', 'caverna'],
    'swarm-of-ravens': ['floresta', 'planície', 'montanha', 'cidade'],
    'swarm-of-spiders': ['floresta', 'selva', 'caverna', 'subterrâneo'],
    'swarm-of-wasps': ['floresta', 'selva', 'planície'],
    'tarrasque': ['planície', 'montanha', 'ruínas', 'deserto'],
    'thug': ['todos'],
    'tiger': ['selva', 'floresta', 'planície'],
    'treant': ['floresta', 'selva'],
    'tribal-warrior': ['todos'],
    'triceratops': ['selva', 'planície'],
    'troll': ['caverna', 'subterrâneo', 'pântano', 'montanha', 'ruínas'],
    'tyrannosaurus-rex': ['selva', 'planície'],
    'unicorn': ['floresta', 'selva'],
    'vampire-bat-form': ['castelo', 'cemitério', 'ruínas', 'cidade'],
    'vampire-mist-form': ['castelo', 'cemitério', 'ruínas', 'cidade'],
    'vampire-spawn': ['castelo', 'cemitério', 'ruínas', 'cidade', 'subterrâneo'],
    'vampire-vampire-form': ['castelo', 'cemitério', 'ruínas', 'cidade', 'subterrâneo'],
    'veteran': ['todos'],
    'violet-fungus': ['caverna', 'subterrâneo'],
    'vrock': ['subterrâneo', 'ruínas', 'vulcão'],
    'vulture': ['deserto', 'planície', 'montanha', 'céu'],
    'warhorse': ['planície', 'cidade'],
    'warhorse-skeleton': ['cemitério', 'ruínas', 'subterrâneo'],
    'water-elemental': ['mar', 'pântano', 'subterrâneo'],
    'weasel': ['floresta', 'planície', 'selva'],
    'werebear-bear-form': ['floresta', 'montanha'],
    'werebear-human-form': ['floresta', 'montanha', 'cidade'],
    'werebear-hybrid-form': ['floresta', 'montanha'],
    'wereboar-boar-form': ['floresta', 'planície'],
    'wereboar-human-form': ['floresta', 'planície', 'cidade'],
    'wereboar-hybrid-form': ['floresta', 'planície'],
    'wererat-human-form': ['cidade', 'subterrâneo', 'ruínas'],
    'wererat-hybrid-form': ['cidade', 'subterrâneo', 'ruínas'],
    'wererat-rat-form': ['cidade', 'subterrâneo', 'ruínas'],
    'weretiger-human-form': ['selva', 'floresta', 'cidade'],
    'weretiger-hybrid-form': ['selva', 'floresta'],
    'weretiger-tiger-form': ['selva', 'floresta'],
    'werewolf-human-form': ['floresta', 'planície', 'cidade'],
    'werewolf-hybrid-form': ['floresta', 'planície'],
    'werewolf-wolf-form': ['floresta', 'planície'],
    'white-dragon-wyrmling': ['caverna', 'montanha', 'ruínas'],
    'wight': ['cemitério', 'ruínas', 'subterrâneo'],
    'will-o-wisp': ['pântano', 'cemitério', 'ruínas'],
    'winter-wolf': ['tundra', 'montanha', 'planície'],
    'wolf': ['floresta', 'planície', 'montanha', 'tundra'],
    'worg': ['floresta', 'planície', 'montanha'],
    'wraith': ['cemitério', 'ruínas', 'subterrâneo'],
    'wyvern': ['montanha', 'planície', 'ruínas'],
    'xorn': ['subterrâneo', 'montanha', 'caverna'],
    'young-black-dragon': ['caverna', 'montanha', 'ruínas'],
    'young-blue-dragon': ['caverna', 'montanha', 'ruínas'],
    'young-brass-dragon': ['caverna', 'montanha', 'ruínas'],
    'young-bronze-dragon': ['caverna', 'montanha', 'ruínas'],
    'young-copper-dragon': ['caverna', 'montanha', 'ruínas'],
    'young-gold-dragon': ['caverna', 'montanha', 'ruínas'],
    'young-green-dragon': ['caverna', 'montanha', 'ruínas'],
    'young-red-dragon': ['caverna', 'montanha', 'ruínas'],
    'young-silver-dragon': ['caverna', 'montanha', 'ruínas'],
    'young-white-dragon': ['caverna', 'montanha', 'ruínas'],
    'zombie': ['cemitério', 'ruínas', 'subterrâneo', 'cidade'],
    };