export const monsterNames: Record<string, string> = {
    "Aboleth": "Aboleth",
    "Acolyte": "Acólito",
    "Adult Black Dragon": "Dragão Negro Adulto",
    "Adult Blue Dragon": "Dragão Azul Adulto",
    "Adult Brass Dragon": "Dragão de Lata Adulto",
    "Adult Bronze Dragon": "Dragão de Bronze Adulto",
    "Adult Copper Dragon": "Dragão de Cobre Adulto",
    "Adult Gold Dragon": "Dragão Dourado Adulto",
    "Adult Green Dragon": "Dragão Verde Adulto",
    "Adult Red Dragon": "Dragão Vermelho Adulto",
    "Adult Silver Dragon": "Dragão Prateado Adulto",
    "Adult White Dragon": "Dragão Branco Adulto",
    "Air Elemental": "Elemental de Ar",
    "Ancient Black Dragon": "Dragão Negro Ancião",
    "Ancient Blue Dragon": "Dragão Azul Ancião",
    "Ancient Brass Dragon": "Dragão de Lata Ancião",
    "Ancient Bronze Dragon": "Dragão de Bronze Ancião",
    "Ancient Copper Dragon": "Dragão de Cobre Ancião",
    "Ancient Gold Dragon": "Dragão Dourado Ancião",
    "Ancient Green Dragon": "Dragão Verde Ancião",
    "Ancient Red Dragon": "Dragão Vermelho Ancião",
    "Ancient Silver Dragon": "Dragão Prateado Ancião",
    "Ancient White Dragon": "Dragão Branco Ancião",
    "Androsphinx": "Androsphinx",
    "Animated Armor": "Armadura Animada",
    "Ankheg": "Ankheg",
    "Ape": "Macaco",
    "Archmage": "Arquimago",
    "Assassin": "Assassino",
    "Awakened Shrub": "Shrub Animado",
    "Awakened Tree": "Árvore Animada",
    "Axe Beak": "Dodô",
    "Azer": "Azer",
    "Baboon": "Babuíno",
    "Badger": "Texugo",
    "Balor": "Balor",
    "Bandit": "Bandido",
    "Bandit Captain": "Capitão dos Bandidos",
    "Barbed Devil": "Diabo Espinhoso",

    "Basilisk": "Basilisco",
    "Bat": "Morcego",
    "Bearded Devil": "Diabo Barbudo",
    "Behir": "Behir",
    "Berserker": "Berserker",
    "Black Bear": "Urso Negro",
    "Black Dragon Wyrmling": "Filhote de Dragão Negro",
    "Black Pudding": "Gosma Negra",
    "Blink Dog": "Cão Pestaneja",
    "Blood Hawk": "Falcão Sangrento",
    "Blue Dragon Wyrmling": "Filhote de Dragão Azul",
    "Boar": "Javali",
    "Bone Devil": "Diabo Ossudo",
    "Brass Dragon Wyrmling": "Filhote de Dragão de Latão",
    "Bronze Dragon Wyrmling": "Filhote de Dragão de Bronze",
    "Brown Bear": "Urso Pardo",
    "Bugbear": "Bugbear",
    "Bulette": "Bulette",
    "Camel": "Camelo",
    "Cat": "Gato",
    "Centaur": "Centauro",
    "Chain Devil": "Diabo das Correntes",
    "Chimera": "Quimera",
    "Chuul": "Chuul",
    "Clay Golem": "Golem de Argila",
    "Cloaker": "Manto Vivo",
    "Cloud Giant": "Gigante das Nuvens",
    "Cockatrice": "Cocatriz",
    "Commoner": "Camponês",
    "Constrictor Snake": "Cobra Constritora",
    "Copper Dragon Wyrmling": "Filhote de Dragão de Cobre",
    "Couatl": "Couatl",
    "Crab": "Caranguejo",
    "Crocodile": "Crocodilo",
    "Cult Fanatic": "Fanático do Culto",
    "Cultist": "Cultista",
    "Darkmantle": "Manto Sombrio",
    "Death Dog": "Cão da Morte",
    "Deep Gnome (Svirfneblin)": "Gnomo das Profundezas (Svirfneblin)",
    "Deer": "Cervo",
    "Deva": "Deva",
    "Dire Wolf": "Lobo Atroz",
    "Djinni": "Gênio (Djinni)",
    "Doppelganger": "Doppelganger",
    "Draft Horse": "Cavalo de Carga",
    "Dragon Turtle": "Tartaruga Dragão",
    "Dretch": "Dretch",
    "Drider": "Drider",
    "Drow": "Elfo Negro",
    "Druid": "Druida",
    "Dryad": "Dríade",
    "Duergar": "Duergar",
    "Dust Mephit": "Mefite de Poeira",
    "Eagle": "Águia",
    "Earth Elemental": "Elemental da Terra",
    "Efreeti": "Efreeti",
    "Elephant": "Elefante",
    "Elk": "Alce",
    "Erinyes": "Erinyes",
    "Ettercap": "Ettercap",
    "Ettin": "Ettin",
    "Fire Elemental": "Elemental do Fogo",
    "Fire Giant": "Gigante do Fogo",
    "Flesh Golem": "Golem de Carne",
    "Flying Snake": "Cobra Voadora",
    "Flying Sword": "Espada Voadora",
    "Frog": "Sapo",
    "Frost Giant": "Gigante do Gelo",
    "Gargoyle": "Gárgula",
    "Gelatinous Cube": "Cubo Gelatinoso",
    "Ghast": "Ghast",
    "Ghost": "Fantasma",
    "Ghoul": "Carniçal",
    "Giant Ape": "Macaco Gigante",
    "Giant Badger": "Texugo Gigante",
    "Giant Bat": "Morcego Gigante",
    "Giant Boar": "Javali Gigante",
    "Giant Centipede": "Centopeia Gigante",
    "Giant Constrictor Snake": "Cobra Constritora Gigante",
    "Giant Crab": "Caranguejo Gigante",
    "Giant Crocodile": "Crocodilo Gigante",
    "Giant Eagle": "Águia Gigante",
    "Giant Elk": "Alce Gigante",
    "Giant Fire Beetle": "Besouro de Fogo Gigante",
    "Giant Frog": "Sapo Gigante",
    "Giant Goat": "Cabra Gigante",
    "Giant Hyena": "Hiena Gigante",
    "Giant Lizard": "Lagarto Gigante",
    "Giant Octopus": "Polvo Gigante",
    "Giant Owl": "Coruja Gigante",
    "Giant Poisonous Snake": "Cobra Venenosa Gigante",
    "Giant Rat": "Rato Gigante",
    "Giant Rat (Diseased)": "Rato Gigante (Doente)",
    "Giant Scorpion": "Escorpião Gigante",
    "Giant Sea Horse": "Cavalo-Marinho Gigante",
    "Giant Shark": "Tubarão Gigante",
    "Giant Spider": "Aranha Gigante",
    "Giant Toad": "Sapo Gigante",
    "Giant Vulture": "Abutre Gigante",
    "Giant Wasp": "Vespa Gigante",
    "Giant Weasel": "Doninha Gigante",
    "Giant Wolf Spider": "Aranha Lobo Gigante",
    "Gibbering Mouther": "Boca Balbuciante",
    "Glabrezu": "Glabrezu",
    "Gladiator": "Gladiador",
    "Gnoll": "Gnoll",
    "Goat": "Cabra",
    "Goblin": "Goblin",
    "Gold Dragon Wyrmling": "Filhote de Dragão Dourado",
    "Gorgon": "Górgona",
    "Gray Ooze": "Gosma Cinzenta",
    "Green Dragon Wyrmling": "Filhote de Dragão Verde",
    "Green Hag": "Bruxa Verde",
    "Grick": "Grick",
    "Griffon": "Grifo",
    "Grimlock": "Grimlock",
    "Guard": "Guarda",
    "Guardian Naga": "Naga Guardiã",
    "Gynosphinx": "Esfinge Fêmea",
    "Half-Red Dragon Veteran": "Veterano Meio-Dragão Vermelho",
    "Harpy": "Harpia",
    "Hawk": "Falcão",
    "Hell Hound": "Cão Infernal",
    "Hezrou": "Hezrou",
    "Hill Giant": "Gigante das Colinas",
    "Hippogriff": "Hipogrifo",
    "Hobgoblin": "Hobgoblin",
    "Homunculus": "Homúnculo",
    "Horned Devil": "Diabo Cornudo",
    "Hunter Shark": "Tubarão Caçador",
    "Hydra": "Hidra",
    "Hyena": "Hiena",
    "Ice Devil": "Diabo de Gelo",
    "Ice Mephit": "Mefite de Gelo",
    "Imp": "Diabrete",
    "Invisible Stalker": "Perseguidor Invisível",
    "Iron Golem": "Golem de Ferro",
    "Jackal": "Chacal",
    "Killer Whale": "Orca",
    "Knight": "Cavaleiro",
    "Kobold": "Kobold",
    "Kraken": "Kraken",
    "Lamia": "Lâmia",
    "Lemure": "Lêmure",
    "Lich": "Lich",
    "Lion": "Leão",
    "Lizard": "Lagarto",
    "Lizardfolk": "Homem-Lagarto",
    "Mage": "Mago",
    "Magma Mephit": "Mefite de Magma",
    "Magmin": "Magmin",
    "Mammoth": "Mamute",
    "Manticore": "Mantícora",
    "Marilith": "Marilith",
    "Mastiff": "Mastim",
    "Medusa": "Medusa",
    "Merfolk": "Tritão",
    "Merrow": "Merrow",
    "Mimic": "Mímico",
    "Minotaur": "Minotauro",
    "Minotaur Skeleton": "Esqueleto de Minotauro",
    "Mule": "Mula",
    "Mummy": "Múmia",
    "Mummy Lord": "Senhor das Múmias",
    "Nalfeshnee": "Nalfeshnee",
    "Night Hag": "Bruxa Noturna",
    "Nightmare": "Pesadelo",
    "Noble": "Nobre",
    "Ochre Jelly": "Geleia Ocre",
    "Octopus": "Polvo",
    "Ogre": "Ogro",
    "Ogre Zombie": "Zumbi Ogro",
    "Oni": "Oni",
    "Orc": "Orc",
    "Otyugh": "Otyugh",
    "Owl": "Coruja",
    "Owlbear": "Corujurso",
    "Panther": "Pantera",
    "Pegasus": "Pégaso",
    "Phase Spider": "Aranha Etérea",
    "Pit Fiend": "Demônio Abissal",
    "Planetar": "Planetário",
    "Plesiosaurus": "Plesiossauro",
    "Poisonous Snake": "Cobra Venenosa",
    "Polar Bear": "Urso Polar",
    "Pony": "Pônei",
    "Priest": "Sacerdote",
    "Pseudodragon": "Pseudodragão",
    "Purple Worm": "Verme Púrpura",
    "Quasit": "Quasit",
    "Quipper": "Peixe Quipper",
    "Rakshasa": "Rakshasa",
    "Rat": "Rato",
    "Raven": "Corvo",
    "Red Dragon Wyrmling": "Filhote de Dragão Vermelho",
    "Reef Shark": "Tubarão de Recife",
    "Remorhaz": "Remorhaz",
    "Rhinoceros": "Rinoceronte",
    "Riding Horse": "Cavalo de Montaria",
    "Roc": "Roc",
    "Roper": "Estrangulador",
    "Rug of Smothering": "Tapete Suffocante",
    "Rust Monster": "Monstro Ferrugem",
    "Saber-Toothed Tiger": "Tigre Dente-de-Sabre",
    "Sahuagin": "Sahuagin",
    "Salamander": "Salamandra",
    "Satyr": "Sátiro",
    "Scorpion": "Escorpião",
    "Scout": "Batedor",
    "Sea Hag": "Bruxa do Mar",
    "Sea Horse": "Cavalo-Marinho",
    "Shadow": "Sombra",
    "Shambling Mound": "Montículo Cambaleante",
    "Shield Guardian": "Guardião de Escudo",
    "Shrieker": "Gritador",
    "Silver Dragon Wyrmling": "Filhote de Dragão Prateado",
    "Skeleton": "Esqueleto",
    "Solar": "Solar",
    "Specter": "Espectro",
    "Spider": "Aranha",
    "Spirit Naga": "Naga Espiritual",
    "Sprite": "Duende",
    "Spy": "Espião",
    "Steam Mephit": "Mefite de Vapor",
    "Stirge": "Sanguessuga Alada",
    "Stone Giant": "Gigante de Pedra",
    "Stone Golem": "Golem de Pedra",
    "Storm Giant": "Gigante da Tempestade",
    "Succubus/Incubus": "Súcubo/Íncubo",
    "Swarm of Bats": "Enxame de Morcegos",
    "Swarm of Beetles": "Enxame de Besouros",
    "Swarm of Centipedes": "Enxame de Centopeias",
    "Swarm of Insects": "Enxame de Insetos",
    "Swarm of Poisonous Snakes": "Enxame de Cobras Venenosas",
    "Swarm of Quippers": "Enxame de Quippers",
    "Swarm of Rats": "Enxame de Ratos",
    "Swarm of Ravens": "Enxame de Corvos",
    "Swarm of Spiders": "Enxame de Aranhas",
    "Swarm of Wasps": "Enxame de Vespas",
    "Tarrasque": "Tarrasque",
    "Thug": "Bandido",
    "Tiger": "Tigre",
    "Treant": "Árvore Anciã",
    "Tribal Warrior": "Guerreiro Tribal",
    "Triceratops": "Tricerátopo",
    "Troll": "Troll",
    "Tyrannosaurus Rex": "Tiranossauro Rex",
    "Unicorn": "Unicórnio",
    "Vampire, Bat Form": "Vampiro (Forma de Morcego)",
    "Vampire, Mist Form": "Vampiro (Forma de Névoa)",
    "Vampire Spawn": "Gerado de Vampiro",
    "Vampire, Vampire Form": "Vampiro (Forma Humanoide)",
    "Veteran": "Veterano",
    "Violet Fungus": "Fungo Violeta",
    "Vrock": "Vrock",
    "Vulture": "Abutre",
    "Warhorse": "Cavalo de Guerra",
    "Warhorse Skeleton": "Esqueleto de Cavalo de Guerra",
    "Water Elemental": "Elemental da Água",
    "Weasel": "Doninha",
    "Werebear, Bear Form": "Ursocida (Forma de Urso)",
    "Werebear, Human Form": "Ursocida (Forma Humana)",
    "Werebear, Hybrid Form": "Ursocida (Forma Híbrida)",
    "Wereboar, Boar Form": "Javalicida (Forma de Javali)",
    "Wereboar, Human Form": "Javalicida (Forma Humana)",
    "Wereboar, Hybrid Form": "Javalicida (Forma Híbrida)",
    "Wererat, Human Form": "Raticida (Forma Humana)",
    "Wererat, Hybrid Form": "Raticida (Forma Híbrida)",
    "Wererat, Rat Form": "Raticida (Forma de Rato)",
    "Weretiger, Human Form": "Tigrícida (Forma Humana)",
    "Weretiger, Hybrid Form": "Tigrícida (Forma Híbrida)",
    "Weretiger, Tiger Form": "Tigrícida (Forma de Tigre)",
    "Werewolf, Human Form": "Licantropo (Forma Humana)",
    "Werewolf, Hybrid Form": "Licantropo (Forma Híbrida)",
    "Werewolf, Wolf Form": "Licantropo (Forma de Lobo)",
    "White Dragon Wyrmling": "Filhote de Dragão Branco",
    "Wight": "Espectro",
    "Will-o'-Wisp": "Fogo-Fátuo",
    "Winter Wolf": "Lobo Invernal",
    "Wolf": "Lobo",
    "Worg": "Worg",
    "Wraith": "Aparição",
    "Wyvern": "Wyvern",
    "Xorn": "Xorn",
    "Young Black Dragon": "Dragão Negro Jovem",
    "Young Blue Dragon": "Dragão Azul Jovem",
    "Young Brass Dragon": "Dragão de Latão Jovem",
    "Young Bronze Dragon": "Dragão de Bronze Jovem",
    "Young Copper Dragon": "Dragão de Cobre Jovem",
    "Young Gold Dragon": "Dragão Dourado Jovem",
    "Young Green Dragon": "Dragão Verde Jovem",
    "Young Red Dragon": "Dragão Vermelho Jovem",
    "Young Silver Dragon": "Dragão Prateado Jovem",
    "Young White Dragon": "Dragão Branco Jovem",
    "Zombie": "Zumbi",
};
